### ISSUE TITLE
Missing /xkcd directive

### ISSUE THREAD

**Issue by neopostmodern** [adimania/telegram-xkcd_bot#1]
In group chats it's currently impossible to use XKCD bot, because bots don't get access to group messages (which is good actually).
Could you add a `/xkcd` directive to direct messages at XKCD and thus enable to use her in groups?

**Comment by jeichelbaum** [comment]
@neopostmodern word!

**Comment by adimania** [comment]
give it a shot. I have added /xkcd directive.

**Comment by pleonex** [comment]
It is working fine for me. Thanks!
